### ISSUE TITLE
0.9.7-pre testing impression

### ISSUE THREAD

**Issue by ni1chigo2115** [retroluxfilm/reshade-vrtoolkit#12]
I think the menu UI is too dark. (Perhaps less transparent?).
Also, the OVR app called Desktop+ took precedence in the display order, perhaps because it was too far away.
This problem caused the Reshade menu to go behind OVR, which made it a bit difficult to set up.
The basic preset shaders worked fine.
I added an additional SMAA here, but this one crashes when entering the world with the video. (I'll probably need to write a fix, but that's not really relevant to this shader)

Translated with www.DeepL.com/Translator (free version)

**Comment by retroluxfilm** [comment]
Sorry for the very late reply and thx for your Feedback.

Tested it with Desktop+ (new ui beta) and it seems to work without issues with the current reshade version. 
The overlay menu UI is indeed a bit to dark for some reason but thats not a big issue and crosire and the reshade community might look into at some point.

Adding other post AA methods that use more than one pass does not really fit this shader. Generally post AA methods are not really working out in VR as they blur to much the fine detail.
