### ISSUE TITLE
Doesn't Work in No Man's Sky VR Mode, But Works in No Man's Sky Desktop Mode Instead

### ISSUE THREAD

**Issue by GT500org** [retroluxfilm/reshade-vrtoolkit#17]
When trying VRToolkit 1.0.0 (or vanilla ReShade 5.0.X) with No Man's Sky, not only does the ReShade button not appear in the dashboard, but the effects are clearly not present in the VR output displayed in the HMD. Effects are only displayed in the desktop mirror window, and not in VR.

I noticed that ReShade 5.0.X also does not work with Half Life Alyx when the Vulkan render API is selected in the settings. Is this an issue with VR games that use the Vulkan API, and not an issue with a specific game?

**Comment by GT500org** [comment]
Almost forgot the log file from VRToolkit 1.0.0 when attempting to use it with No Man's Sky:
[ReShade.log](https://github.com/retroluxfilm/reshade-vrtoolkit/files/8312407/ReShade.log)

**Comment by GT500org** [comment]
> But I remember that HL Alyx it worked with the VR toolkit (kernel32.dll) the same way as the DirectX renderer.

I use kernel32.dll as the name for the ReShade64.dll file with Half Life Alyx (it doesn't seem to work in DirectX 11 mode any other way), and it didn't work when the game was using Vulkan when named kernel32.dll (I think it was injecting, but no shader effects were appearing in the game's VR view).

I can't remember if I used the ReShade installer to try to configure Half Life Alyx for Vulkan the last time I tested it. I will try again to see if that has any effect, but I do know for certain that I did try it with No Man's Sky before testing VRToolkit.

**Comment by GT500org** [comment]
FYI: It looks like I had installed ReShade correctly for Vulkan support for Half Life Alyx:

```{
    "file_format_version": "1.1.2",
    "layer": {
        "name": "VK_LAYER_LUNARG_override",
        "type": "GLOBAL",
        "api_version": "1.2.198",
        "implementation_version": "1",
        "description": "ReShade Override Layer",
        "disable_environment": {
            "DISABLE_VK_LAYER_reshade_1": "1"
        },
        "app_keys": [
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\StrangeBrigade\\bin\\StrangeBrigade_Vulkan.exe",
            "C:\\Program Files (x86)\\Ubisoft\\Ubisoft Game Launcher\\games\\Ghost Recon Breakpoint\\GRB_vulkan.exe",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\ZombieArmy4\\bin\\za4_vulkan.exe",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Half-Life Alyx\\game\\bin\\win64\\hlvr.exe"
        ],
        "override_paths": [
            "C:\\Users\\GT500\\AppData\\Local\\ReShade\\ReShade64"
        ],
        "component_layers": [
            "VK_LAYER_reshade"
        ]
    }
}
```

BTW: Is there anywhere that I can report ReShade VR bugs? VR related comments in the Discord seem to generally get ignored, and I can't sign up for the forums (no clue why as there's no error, no e-mail confirmation, and no indication as to whether it even tried to create an account).

**Comment by retroluxfilm** [comment]
I still think that reshade does not work yet for Vulkan in VR but it might be related on how it installs. Crosire has updated reshade to 5.1 with another change to the vulkan installation method with the setup. You could give it a try.

I guess the best place to ask for reshade help is still the discord (https://discord.com/channels/586242553746030596/609352379351171076) or the official forum.

**Comment by GT500org** [comment]
> Crosire has updated reshade to 5.1 with another change to the vulkan installation method with the setup. You could give it a try.

I'll check and see if it works with 5.1.0 and report back.


> I guess the best place to ask for reshade help is still the discord (...) or the official forum.

So that's a "no" then. OK.

**Comment by GT500org** [comment]
> I'll check and see if it works with 5.1.0 and report back.

I should probably mention that none of the updates to ReShade have had any effect on it not working with Vulkan games in VR. I kept forgetting about this bug report, so I didn't report back earlier.

**Comment by retroluxfilm** [comment]
No worries. Seems that the Vulkan VR implementation is simply not working in reshade. Currently dont have the time to look into it. But i am sure that the reshade dev together with the community might work on it at some point.

**Comment by GT500org** [comment]
I'll close this for now, since it's specifically a ReShade issue.
