### ISSUE TITLE
Not working in F1 22 VR

### ISSUE THREAD

**Issue by kmj007** [retroluxfilm/reshade-vrtoolkit#18]
As soon as the race starts, opening Reshade overlay causes the whole game to CTD. And this game desperately needs a sharpening filter. I tried both VRToolkit and newest official Reshade. Game acknowledges Reshade after renaming dxgi to dinput8, just like in last Codemasters VR title - Dirt Rally 2. (Steam version)
Anyone has an idea how to make this work? I hope it's the place to ask, I tried everything I could think of but so far no luck.

**Comment by retroluxfilm** [comment]
Sorry for the late reply.

Sadly I dont have the game to give you tips on how to solve it. If reshade is already picked up the log file (dxgi.log or dinput8.log) might give some clues why it has crashed.
Does it crash only in VR or also on the 2D gameplay with reshade and the same shaders activated?
When it crashes in VR, which reshade overlay are you opening. The one in the StreamVR dashboard like described here? https://vrtoolkit.retrolux.de/configuration.html

It might be best to ask in the reshade discord. There might be already a fix for it in dev branch or they dont know about the issue.

**Comment by kmj007** [comment]
Thanks for your reply. Reshade works on 2D display. In VR it crashes when I open Reshade overlay in the SteamVR Dashboard. Here's my Reshade log from my last try.
[ReShade.log](https://github.com/retroluxfilm/reshade-vrtoolkit/files/9078117/ReShade.log)
I just noticed it's from Reshade 5.2.1.1510, but the same thing was happening with 5.2.2 and VRToolkit.

**Comment by retroluxfilm** [comment]
In the log file i could not see the reason why it crashed. Reshade simpliy exited and unloaded the hooks.

Do you try to just use the vrtoolkit package without any other shaders and checked if reshade is working itself in VR without opening the reshade dashboard? You can edit the reshade.ini and set a stonger sharpening preset like the generic_vr+.ini to better see if it is actually working.

Could be that the crash is only related to the Imgui rendering for the reshade steamvr dashboard widget.

**Comment by retroluxfilm** [comment]
The latest reshade 5.3.0 has fixed the crash issue on F1 22
https://reshade.me/releases/8153-5-3

**Comment by kmj007** [comment]
Thx, great find, I'll check it out :)

**Comment by retroluxfilm** [comment]
Thanks for letting me know @kmj007 . Guess I need to update vrtoolkit package for easy usage again.
