### ISSUE TITLE
Shaders are only applied to game window and not in headset

### ISSUE THREAD

**Issue by Austint30** [retroluxfilm/reshade-vrtoolkit#23]
Game: Project Cars 2
VR Software: SteamVR
Headset: Valve Index
OS: Windows 11
GPU: Nvidia RTX 20760 Super

Files were installed to the Project Cars 2 root directory and ReShade64.dll was renamed to dinput8.dll.
I am able to access the reshade UI and change the shader settings. However, the shaders are only applied to the game window and not in the headset. Doesn't work if I enable performance mode either.

The reshade icon doesn't appear in the SteamVR menu either.

**Comment by Austint30** [comment]
Alright so I managed to get it to work by using the official reshade at reshade.me rather than using this. I was able to install the VRTooklit shaders through there and it's all working as expected.

**Comment by retroluxfilm** [comment]
Great to hear that you got it working. Usually it worked for me with the index. But could be that the last release has broken it that i released here.  But its better to use the official reshade version as it also contains a few fixes in VR that are not bundled in the vrtoolkit yet. Enjoy the increased clarity in Project Cars 2 :)

**Comment by NapherZ** [comment]
Hello retrolux! I have the same problem in assetto corsa competition, the vrtoolkit works for me on the screen but it does not appear in the VR glasses. I do not know what to do now.

**Comment by NapherZ** [comment]
> Great to hear that you got it working. Usually it worked for me with the index. But could be that the last release has broken it that i released here. But its better to use the official reshade version as it also contains a few fixes in VR that are not bundled in the vrtoolkit yet. Enjoy the increased clarity in Project Cars 2 :)

Hello retrolux! I have the same problem in assetto corsa competition, the vrtoolkit works for me on the screen but it does not appear in the VR glasses. I do not know what to do now.

**Comment by retroluxfilm** [comment]
If you use openXR toolkit for example you need to use the Reshade preview installer from the latest release.
See: https://vrtoolkit.retrolux.de/install.html

Over regular SteamVR it works for me with the Valve Index

**Comment by NapherZ** [comment]
> If you use openXR toolkit for example you need to use the Reshade preview installer from the latest release. See: https://vrtoolkit.retrolux.de/install.html
> 
> Over regular SteamVR it works for me with the Valve Index

I don't use open xr, I only use steam VR, and it works for me in ams2, RF2, DirtRally 2.0 but in ACC it doesn't appear in the steam VR menu

**Comment by retroluxfilm** [comment]
Thats odd. Make sure to get into the cockpit of the car to get a real 3d scene. Only then reshade gets enabled (visible as icon in the dashboard)

**Comment by NapherZ** [comment]
> Thats odd. Make sure to get into the cockpit of the car to get a real 3d scene. Only then reshade gets enabled (visible as icon in the dashboard)

That's what I do, when I'm in the cabin I open the steam vr menu and it doesn't appear. With this latest version, is it not necessary to rename any files? because only the program is downloaded... it is no longer a zip like before.

**Comment by NapherZ** [comment]
Can you try to see if it works for you in AC competition and tell me how you did it?

**Comment by retroluxfilm** [comment]
You dont need to use the installer just the zip file of you dont use openXR and follow the install instructions.
https://github.com/retroluxfilm/reshade-vrtoolkit/releases/download/v1.1.0/VRToolkitReshadeUniversal_1.1.0.zip

**Comment by retroluxfilm** [comment]
Here you can see in what folder you need to extract the zip and then rename the Reshade64.dll to dxgi.dll
![grafik](https://github.com/retroluxfilm/reshade-vrtoolkit/assets/85709777/18ca6bd7-8c46-4487-827c-8984ef18e379)

**Comment by NapherZ** [comment]
> No necesita usar el instalador, solo el archivo zip de no usar openXR y siga las instrucciones de instalación. https://github.com/retroluxfilm/reshade-vrtoolkit/releases/download/v1.1.1/VRToolkitReshadeUniversal_1.1.1.zip

Hello! It already works for me, I was missing a file that I deleted from the game, that zip that you have passed me is not downloaded directly from the vrtoolkit page, on the page only the installer is downloaded reshade.me that's why I couldn't get it to work for this too, you must include that zip in the download from the vrtoolkit page. Thanks for everything.

**Comment by Pavelo77** [comment]
After multiple tries I finally managed to make it work with Dirt Rally 2.0, still no luck with Automobilista 2 and Dirt Rally (with Revive, launches in SteamVR), reshade loads regularly but the effects are applied only in the window but not in the visor (Quest 2), any advice? thanks

**Comment by retroluxfilm** [comment]
@Pavelo77 for AMS2 you need to name the reshade dll to dinput8.dll
See the gamelist for a hint on what to do on certain games
https://vrtoolkit.retrolux.de/gamelist.html

**Comment by Pavelo77** [comment]
I did it, I read carefully all the instructions, installed the latest ReShade version and renamed the 64bit dll into dinput8.dll, no go
