### ISSUE TITLE
I miss FXAA :(

### ISSUE THREAD

**Issue by WizzDude** [retroluxfilm/reshade-vrtoolkit#26]
I used the FXAA included in this shader for H3VR because it ran much faster than MSAA and did not look much worse.

It can absolutely suck in VR, and I could see why it was removed, but it is not entirely useless. H3VR's environments are mostly made up of very simple geometry that FXAA can anti-alias just fine. Especially if you max out the quality at 39 and leave the default settings as-is (I noticed absolutely zero difference in performance between the quality at 10 vs. the quality at 39, stayed at 2.9ms in the same spot).

I really freed up lots of performance headroom with FXAA. It still ran faster in this shader than it does when I add it afterwards as a separate shader (3.6ms compared to 2.9ms).

Can you add it back so that I can update to the latest version? If not, I would really love a more specific explanation as to why it's gone.

**Comment by retroluxfilm** [comment]
It was removed as it did not had the bug improvement I hoped it to have. (Simracing) The FXAA I added to the toolkit was a lower quality variant to able to work in a single pass to save peformance. I honestly did not thought that anyone would have a usecase for it. You can always add the FXAA, SMAA or DLAA as a extra shader before applying the vrtoolkit. I found DLAA was acually not bad in VR but a little more expensive. Still not as much as MSAA for sure.

I can re-add FXAA to the VRtoolkit though if you want it. (Was removed to just clean up the shader code) 
But first try to use the FXAA etc. seperatly if it works for you?

**Comment by WizzDude** [comment]
I was trying other solutions, including DLAA, but they were all less efficient than the game’s MSAA and looked about the same as 2X MSAA.

**Comment by retroluxfilm** [comment]
I will re-add it later for you again if it has a good use. Right now you can download the old version here that stil has it:
https://github.com/retroluxfilm/reshade-vrtoolkit/releases/tag/v1.0.0

Just extraxt the shader folder and overwrite the new version.

**Comment by WizzDude** [comment]
hell yeah thanks a lot! Got version 1.0 to work

**Comment by retroluxfilm** [comment]
FXAA is re-added now in the repo
