### ISSUE TITLE
Possibility of Adding SMAA

### ISSUE THREAD

**Issue by LIII-Works** [retroluxfilm/reshade-vrtoolkit#27]
I would like to ask if it is possible to add SMAA (as a option or replacement) in the future versions of VRToolkit?

**Comment by retroluxfilm** [comment]
The vr toolkit shader is trimmed to work in a single pass for high performance. SMAA sadly is a multi pass shader that would not fit into the concept if the vrtoolkit. However you can always use other shader in combination with vrtoolkit and experiment how SMAA or other AA shader would look in VR.
