### ISSUE TITLE
VRChat：Crashes when moving to a world that plays video.

### ISSUE THREAD

**Issue by ni1chigo2115** [retroluxfilm/reshade-vrtoolkit#5]
It's just like the title says.
It crashes in autoplay worlds, and it also crashes if I enter an instance of a world with a video player where someone else is playing a video.
(Cozy Apartment, for example).

**Comment by retroluxfilm** [comment]
As it is a free game i can look into this and debug why it crashes. Thanks for the report.

**Comment by retroluxfilm** [comment]
I can confirm that it crashes with the current reshade build.

**Comment by retroluxfilm** [comment]
Fixed with the latest v0.9.7-pre release version.
