### ISSUE TITLE
Doesn't work with Open Composite 

### ISSUE THREAD

**Issue by m-vlad** [retroluxfilm/reshade-vrtoolkit#6]
something about IVROverlay_25 being unkown/unsupported.

**Comment by retroluxfilm** [comment]
Do you have a game and the open composite version you are using to reproduce the issue you have encountered?

**Comment by m-vlad** [comment]
Skyrim VR, and open composite hasn't updated in a while, just grab the newest system wide launcher

**Comment by m-vlad** [comment]
Btw this seems to be because open composite does not support overlays, so would it be possible to have a toggle for the overlay, so it still works on open composite without trying to render something it can't?

**Comment by retroluxfilm** [comment]
Sorry I did not have the time to test open composite, especially as i have the Valve Index which needs StreamVR.
Did you test the latest Reshade version 5.3.0 if the issue is still present? (Just replace the DLL from the Vrtoolkit release backage)

**Comment by m-vlad** [comment]
No the latest official reshade also has the issue, the only dll i've found that doesn't have the issue is one I got from an early build of reshade for VR, forgot exactly from where, but you can find a copy of it in the mod downloadable from here https://www.nexusmods.com/skyrimspecialedition/mods/47989

**Comment by retroluxfilm** [comment]
Yes thats the first reshade release fholger did on implementing VR. It does not have the streamVR overlays and due to that it does not crash. Guess the ImGui overlay must be optional when steamVR is not loaded avoiding a crash. No time to look into this but hopefully the reshade dev crosire will do it one day for open composite users.
